{{- $clientID := .Values.auth.eclipseClientId }}
kind: Secret
apiVersion: v1
metadata:
  name: git-credentials-secret
  namespace: admin-devspaces
  labels:
    app.kubernetes.io/component: workspace-secret
    app.kubernetes.io/part-of: che.eclipse.org
    controller.devfile.io/git-credential: 'true'
    controller.devfile.io/watch-secret: 'true'
  annotations:
    che.eclipse.org/automount-workspace-secret: 'true'
    che.eclipse.org/git-credential: 'true'
    che.eclipse.org/mount-as: file
    che.eclipse.org/mount-path: /.git-credentials
    che.eclipse.org/scm-url: 'https://github.com/'
    controller.devfile.io/mount-path: /.git-credentials
stringData:
  credentials: {{ printf "https://oauth2:%s@github.com" $clientID }}
type: Opaque
