kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: registry
  labels:
    app: apicurio-registry
spec:
  to:
    kind: Service
    name: apicurio-registry-service
    weight: 100
  port:
    targetPort: http
  tls:
    termination: edge
